Add info for failed nunit tests

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -143,12 +143,15 @@ jobs:
         continue-on-error: true
         run: cat test_output/test*IntegrationTestsBatchMode/*.log
 
-      - name: Obtain Failed tests
+      - name: Obtain Failed tests from Integration tests and NUnit tests
         if: always()
         shell: bash
         continue-on-error: true
         run: |
+          # Quick and dirty way to get all failed tests in granular level.
+          # TODO: better parser for more information, ex. error message.
           cat test_output/test*/*_test.log | { grep "^Test .* FAILED$" || true; }
+          cat test_output/test*/test*/results.xml | { grep '^ *<test-case.*result="Failed"' || true; } | sed 's/^.* name="\([^\"]*\)".*$/Test \1: FAILED/'
 
       - name: Return Unity license
         if: always()
